# Site settings
name: La Coroutine
email: contact@lacorotuine.org
title: "La Coroutine | Coworking et Salle de Réunion à Lille | Créer, apprendre, partager "
description: > # this means to ignore newlines until "baseurl:"
  Un espace de coworking convivial créé, géré et financé par ses usagers pour créer
  travailler, bidouiller, apprendre, innover, partager, échanger, ...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lacoroutine.org" # the base hostname & protocol for your site
twitter: lacoroutine
github: la-coroutine

# Build settings
sass:
  sass_dir: _sass
  style: compressed
